- Importação das Bibliotecas

In [41]:
import pandas as pd
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [42]:
tabela = pd.read_excel('challenge.xlsx')
display(tabela)

,First Name,Last Name,Company Name,Role in Company,Address,Email,Phone Number
0,John,Smith,IT Solutions,Analyst,98 North Road,jsmith@itsolutions.co.uk,40716543298
1,Jane,Dorsey,MediCare,Medical Engineer,11 Crown Street,jdorsey@mc.com,40791345621
2,Albert,Kipling,Waterfront,Accountant,22 Guild Street,kipling@waterfront.com,40735416854
3,Michael,Robertson,MediCare,IT Specialist,17 Farburn Terrace,mrobertson@mc.com,40733652145
4,Doug,Derrick,Timepath Inc.,Analyst,99 Shire Oak Road,dderrick@timepath.co.uk,40799885412
5,Jessie,Marlowe,Aperture Inc.,Scientist,27 Cheshire Street,jmarlowe@aperture.us,40733154268
6,Stan,Hamm,Sugarwell,Advisor,10 Dam Road,shamm@sugarwell.org,40712462257
7,Michelle,Norton,Aperture Inc.,Scientist,13 White Rabbit Street,mnorton@aperture.us,40731254562
8,Stacy,Shelby,TechDev,HR Manager,19 Pineapple Boulevard,sshelby@techdev.com,40741785214
9,Lara,Palmer,Timepath Inc.,Programmer,87 Orange Street,lpalmer@timepath.co.uk,40731653845

In [43]:
# Criando o navegador
servico = Service(ChromeDriverManager().install())
navegador = webdriver.Chrome(service=servico)

In [ ]:
navegador.get('https://www.rpachallenge.com/')
time.sleep(2)  # Esperar carregar

In [ ]:
#Começar
navegador.find_element(By.XPATH, '//button[@class="waves-effect col s12 m12 l12 btn-large uiColorButton"]')


for i, coluna in tabela.iterrows():
    valor = tabela.iloc[i, ]

    # Email - Busca o Input @ng-reflect-name='labelEmail'
    navegador.find_element(By.XPATH, "//input[@ng-reflect-name='labelEmail']").send_keys(valor['Email'])

    # Company Name = ng-reflect-name="labelCompanyName"
    navegador.find_element(By.XPATH, "//input[@ng-reflect-name='labelCompanyName']").send_keys(valor['Company Name'])

    # lastName = ng-reflect-name="labelLastName"
    navegador.find_element(By.XPATH, "//input[@ng-reflect-name='labelLastName']").send_keys(valor['Last Name '])

    # roleCompany = ng-reflect-name="labelRole"
    navegador.find_element(By.XPATH, "//input[@ng-reflect-name='labelRole']").send_keys(valor['Role in Company'])

    # Phone = ng-reflect-name="labelPhone"
    navegador.find_element(By.XPATH, "//input[@ng-reflect-name='labelPhone']").send_keys(str(valor['Phone Number']))

    # firsName = ng-reflect-name="labelFirstName"
    navegador.find_element(By.XPATH, "//input[@ng-reflect-name='labelFirstName']").send_keys(valor['First Name'])

    # adress = ng-reflect-name="labelAddress"
    navegador.find_element(By.XPATH, "//input[@ng-reflect-name='labelAddress']").send_keys(valor['Address'])

    # submit = 
    navegador.find_element(By.XPATH, "//input[@class='btn uiColorButton']").click()
    time.sleep(2)